# okteto login && okteto namespace && okteto stack deploy - build
name: nb2chan
services:
  nb2chan:
    public: true
    image: nb2chan-dattw/koyeb-nb:nb2chan
    build: .
    replicas: 1
    ports:
      - 8680
    resources:
      cpu: 1000m
      memory: 3Gi
