[tool.poetry]
name = "koyeb-nb2"
version = "0.1.0"
description = "koyeb-nb2"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
# python = "^3.7"
python = "^3.7.3"
nonebot2 = "^2.0.0.a1"
nonebot-plugin-guess = "^0.1.5"
chardet = "^4.0.0"
Jinja2 = "^3.0.1"
nonebot-adapter-cqhttp = "^2.0.0-alpha.13"

[tool.poetry.dev-dependencies]
nonebot-test = "^0.1.0"
poethepoet = "^0.10.0"

[nonebot.plugins]
plugins = []
plugin_dirs = ["koyeb_nb2/plugins"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
